export const state = {
  metrics: {},
  shares: {
    incoming: {},
    outgoing: {},
    accepted: {},
  },
  validUnits: [
    { value: 'cm', text: 'Centimeters' },
    { value: 'm', text: 'Meters' },
    { value: 'km', text: 'Kilometers' },
    { value: 'miles', text: 'Miles' },
    { value: 'kg', text: 'Kilograms' },
    { value: 'st', text: 'Stone' },
    { value: 'lb', text: 'Pounds (weight)' },
    { value: 'GBP', text: 'Pound Sterling' },
    { value: 'inches', text: 'Inches' },
    { value: 'sec', text: 'Seconds' },
    { value: 'min', text: 'Minutes' },
    { value: 'hr', text: 'Hours' },
    { value: 'reps', text: 'Reps' },
    { value: 'qty', text: 'Qty' },
    { value: 'tod', text: 'Time of Day' },
    { value: 'none', text: 'None' },
  ],
};
